(function () {
  const data = window.BAXIAN_DATA;
  const app = document.getElementById("app");
  const state = { screen: "home", index: 0, answers: [], revealStep: 0 };
  let revealTimer;
  const dimensions = { courage: "勇敢", freedom: "洒脱", resilience: "坚韧", empathy: "共情", insight: "洞察", order: "守序" };
  const profiles = {
    "吕洞宾": { courage: 95, freedom: 58, resilience: 78, empathy: 68, insight: 70, order: 72 },
    "钟离权": { courage: 72, freedom: 66, resilience: 70, empathy: 88, insight: 58, order: 60 },
    "铁拐李": { courage: 80, freedom: 54, resilience: 98, empathy: 56, insight: 64, order: 65 },
    "何仙姑": { courage: 55, freedom: 48, resilience: 72, empathy: 98, insight: 90, order: 76 },
    "韩湘子": { courage: 60, freedom: 96, resilience: 62, empathy: 76, insight: 78, order: 42 },
    "曹国舅": { courage: 64, freedom: 38, resilience: 84, empathy: 66, insight: 76, order: 98 },
    "蓝采和": { courage: 68, freedom: 98, resilience: 66, empathy: 78, insight: 52, order: 30 },
    "张果老": { courage: 50, freedom: 72, resilience: 68, empathy: 62, insight: 98, order: 58 }
  };
  const items = [
    [["courage","freedom"],[[2,1],[1,2],[0,2],[1,0]]], [["courage","resilience"],[[0,2],[2,1],[1,1],[1,0]]],
    [["courage","empathy"],[[2,0],[1,1],[0,2],[1,1]]], [["courage","insight"],[[2,0],[1,1],[0,2],[1,0]]],
    [["resilience","empathy"],[[0,2],[2,1],[2,0],[0,1]]], [["freedom","empathy"],[[2,1],[0,1],[1,2],[2,0]]],
    [["freedom","insight"],[[1,0],[2,0],[0,2],[2,1]]], [["courage","order"],[[2,0],[1,1],[1,2],[0,1]]],
    [["freedom","order"],[[0,2],[2,0],[0,2],[2,0]]], [["resilience","insight"],[[1,1],[1,2],[0,2],[2,0]]],
    [["freedom","resilience"],[[0,1],[2,1],[1,2],[2,0]]], [["insight","order"],[[0,2],[2,1],[1,0],[2,2]]],
    [["empathy","insight"],[[1,2],[0,1],[2,1],[1,2]]], [["empathy","order"],[[0,1],[1,0],[2,2],[1,0]]],
    [["resilience","order"],[[0,2],[1,0],[1,1],[2,1]]]
  ];
  function esc(v) { return String(v == null ? "" : v).replace(/[&<>'"]/g, function (c) { return {"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c] || c; }); }
  function save() { try { localStorage.setItem("baxian-test-state", JSON.stringify(state)); } catch (e) {} }
  function restore() { try { const s = JSON.parse(localStorage.getItem("baxian-test-state") || "null"); if (s && Array.isArray(s.answers)) { state.answers = s.answers.slice(0, data.questions.length); state.index = Math.min(Number(s.index) || state.answers.length, data.questions.length); state.screen = state.index >= data.questions.length ? "result" : (s.screen === "quiz" ? "quiz" : "home"); } } catch (e) {} }
  function score() { const out = {}; const count = {}; Object.keys(dimensions).forEach(function (k) { out[k] = 0; count[k] = 0; }); state.answers.forEach(function (answer, i) { const item = items[i]; if (!item || !item[1][answer]) return; item[0].forEach(function (k, j) { out[k] += item[1][answer][j] || 0; count[k] += 1; }); }); Object.keys(out).forEach(function (k) { out[k] = Math.round(out[k] / Math.max(1, count[k] * 2) * 100); }); return out; }
  function distance(a, b) { return Math.sqrt(Object.keys(dimensions).reduce(function (n, k) { const d = (a[k] || 0) - b[k]; return n + d * d; }, 0)); }
  function winner() { const s = score(); return Object.keys(profiles).sort(function (a, b) { return distance(s, profiles[a]) - distance(s, profiles[b]) || a.localeCompare(b, "zh-CN"); })[0]; }
  function similarity(s, p) { const mean = Object.keys(dimensions).reduce(function (n, k) { return n + Math.abs((s[k] || 0) - p[k]); }, 0) / 6; return Math.max(70, Math.min(98, Math.round(100 - mean))); }
  function home() { app.innerHTML = "<section class='page home-page'><div class='home-orb orb-one'></div><div class='home-orb orb-two'></div><div class='topline'><span>八仙 · PERSONALITY MATRIX</span><span>01 — 15</span></div><div class='home-layout'><div><p class='eyebrow'>一场关于选择的东方思想实验</p><h1>如果你也是八仙，<br><em>你会是哪一位？</em></h1><p class='subtitle'>15 道奇遇题，拆解你的勇敢、洒脱与内在底色。</p><div class='intro-card card'><div class='card-kicker'>HOW IT WORKS / 测试方式</div><p>接下来，我们会一起走过 15 个岔路口。你将面对未知、做出取舍、选择同行者，也会在每一次决定里，逐渐看见真正的自己。没有标准答案，凭第一直觉出发，看看走到最后，哪一位八仙与你最像。</p><div class='intro-meta'><span>情境选择</span><span>性格钻石图</span><span>主人格画像</span></div></div><button class='primary-button' data-action='start'>开启思想实验 <span>↗</span></button><p class='hint'>预计用时 3 分钟 · 结果仅供自我探索，不构成心理诊断</p></div><div class='seal-card' aria-label='八仙性格矩阵'><div class='seal-ring'></div><div class='seal-mark'>八<br>仙</div><p>THE<br>EIGHT<br>IMMORTALS</p><span>性格矩阵 · 2026</span></div></div></section>"; }
  function quiz() { const q = data.questions[state.index]; const pct = Math.round((state.index + 1) / data.questions.length * 100); app.innerHTML = "<section class='page quiz-page'><div class='topline'><span>八仙 · PERSONALITY MATRIX</span><span>" + String(state.index + 1).padStart(2, "0") + " / 15</span></div><div class='progress-wrap'><div class='progress'><span style='width:" + pct + "%'></span></div><b>" + pct + "%</b></div><div class='question-layout'><aside class='question-aside'><span>奇遇 " + String(state.index + 1).padStart(2, "0") + "</span><i></i><p>凭第一直觉。<br>没有标准答案。</p></aside><div class='question-main'><p class='eyebrow'>" + esc(q.title) + "</p><h2>" + esc(q.scene) + "</h2><p class='hint'>选择最接近你真实反应的那一项。</p><div class='options'>" + q.options.map(function (o, i) { return "<button class='option' data-option='" + i + "'><span class='option-number'>" + String.fromCharCode(65 + i) + "</span><span>" + esc(o) + "</span><span class='option-arrow'>→</span></button>"; }).join("") + "</div></div></div></section>"; }
  function reveal() { const lines = ["15 个岔路口，已经走到尽头。", "你的每一次选择，都留下了一点线索。", "这些线索正在汇成你的性格轮廓。", "与你最相似的那位八仙……"]; app.innerHTML = "<section class='page reveal-page'><div class='reveal-card'><div class='reveal-mark'>八<br>仙</div><p class='eyebrow'>THE JOURNEY · 旅程回响</p><p class='reveal-line'>" + esc(lines[Math.min(state.revealStep, 3)]) + "</p><p class='reveal-progress'>正在揭晓 " + Math.min(state.revealStep + 1, 4) + " / 4</p></div></section>"; }
  function startReveal() { window.clearTimeout(revealTimer); state.screen = "reveal"; state.revealStep = 0; render(); revealTimer = window.setInterval(function () { state.revealStep += 1; if (state.revealStep >= 4) { window.clearInterval(revealTimer); state.screen = "result"; state.revealStep = 0; render(); } else render(); }, 800); }
  function diamond(s) { const keys = Object.keys(dimensions), cx = 235, cy = 122, r = 86, angle = function (i) { return -Math.PI / 2 + i * Math.PI * 2 / keys.length; }, pt = function (v, i, rr) { const a = angle(i), l = rr * v / 100; return (cx + Math.cos(a) * l).toFixed(1) + "," + (cy + Math.sin(a) * l).toFixed(1); }; const grid = [25,50,75,100].map(function (v) { return "<polygon points='" + keys.map(function (_, i) { return pt(v, i, r); }).join(" ") + "'></polygon>"; }).join(""); const axes = keys.map(function (_, i) { const p = pt(100, i, r).split(","); return "<line x1='" + cx + "' y1='" + cy + "' x2='" + p[0] + "' y2='" + p[1] + "'></line>"; }).join(""); const area = keys.map(function (k, i) { return pt(s[k], i, r); }).join(" "); const dots = keys.map(function (k, i) { const p = pt(s[k], i, r).split(","); return "<circle cx='" + p[0] + "' cy='" + p[1] + "' r='4'></circle>"; }).join(""); const labels = keys.map(function (k, i) { const p = pt(100, i, r + 27).split(","); return "<text x='" + p[0] + "' y='" + p[1] + "' text-anchor='middle'>" + dimensions[k] + "</text>"; }).join(""); return "<div class='diamond-wrap'><svg class='diamond' viewBox='0 0 470 255' role='img' aria-label='六维性格钻石图'><g class='diamond-grid'>" + grid + "</g><g class='diamond-axes'>" + axes + "</g><polygon class='diamond-area' points='" + area + "'></polygon><g class='diamond-points'>" + dots + "</g><g class='diamond-labels'>" + labels + "</g></svg></div>"; }
  function result() { const s = score(), name = winner(), p = data.profiles[name], sim = similarity(s, profiles[name]); app.innerHTML = "<section class='page result-page'><div class='topline'><span>八仙 · PERSONALITY MATRIX</span><span>REPORT / COMPLETE</span></div><div class='result-heading'><p class='eyebrow'>YOUR RESULT · 你的主人格</p><h1>" + esc(name) + "</h1><p class='result-title'>" + esc(p.title) + "</p><p class='result-lead'>你已经走过十五个岔路口。一路上，你如何面对未知、选择同行者、守住信念，也决定了你会成为怎样的人。现在，答案落在了一位八仙身上——看看这一次，命运把你带到了谁的身边。</p></div><div class='card diamond-card'><div class='card-kicker'>PERSONALITY DIAMOND / 性格钻石图</div><h2>你的性格轮廓</h2><p class='section-note'>六个维度共同勾勒你的性格轮廓，再与八仙画像进行整体比较。</p>" + diamond(s) + "</div><div class='card profile-card'><div class='profile-top'><div><div class='card-kicker'>THE CORE / 主人格画像</div><h2>" + esc(name) + " · " + esc(p.title) + "</h2><p class='keywords'>" + esc(p.keywords) + "</p></div><div class='score-stamp'>画像相似度<br><strong>" + sim + "%</strong></div></div><div class='analysis-grid'><div class='analysis-block'><h3>你的性格</h3><p>" + esc(p.description || p.strength || "你在选择中展现出独特而稳定的内在倾向。") + "</p></div><div class='analysis-block'><h3>你的优势</h3><p>" + esc(p.strength || "你能把自己的力量带进真实行动。") + "</p></div><div class='analysis-block'><h3>隐藏弱点</h3><p>" + esc(p.weakness || "有时会把某种优势用得太满，记得给自己留一点弹性。") + "</p></div><div class='analysis-block'><h3>你的人生课题</h3><p>" + esc(p.lesson || "在坚持自我与理解世界之间，找到属于自己的节奏。") + "</p></div></div><blockquote><span class='quote-label'>THE LINE · 你最像的一句话</span>“" + esc(p.quote || "温柔不是软弱，安静也可以很坚定。") + "”</blockquote></div><div class='actions'><button class='primary-button' data-action='share'>复制分享链接 <span>↗</span></button><button class='secondary-button' data-action='restart'>重新进入旅程</button></div><p class='hint' id='share-message'>链接已准备好，复制后可以发给朋友。</p></section>"; }
  function render() { if (state.screen === "home") home(); else if (state.screen === "quiz") quiz(); else if (state.screen === "reveal") reveal(); else result(); save(); window.scrollTo(0, 0); }
  async function share() { const m = document.getElementById("share-message"); try { if (navigator.share) await navigator.share({ title: "八仙性格测试", url: location.href }); else await navigator.clipboard.writeText(location.href); if (m) m.textContent = "链接已复制，可以发给朋友了。"; } catch (e) { if (m) m.textContent = "请手动复制浏览器地址栏链接。"; } }
  app.addEventListener("click", function (e) { const action = e.target.closest("[data-action]") && e.target.closest("[data-action]").dataset.action; const option = e.target.closest("[data-option]") && e.target.closest("[data-option]").dataset.option; if (action === "start") { state.screen = "quiz"; state.index = 0; state.answers = []; state.revealStep = 0; render(); } else if (option !== null && option !== undefined && state.screen === "quiz") { state.answers.push(Number(option)); state.index += 1; if (state.index >= data.questions.length) startReveal(); else render(); } else if (action === "restart") { window.clearTimeout(revealTimer); state.screen = "home"; state.index = 0; state.answers = []; state.revealStep = 0; render(); } else if (action === "share") share(); });
  restore(); render();
})();
